# Generated by Django 5.2.13 on 2026-04-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='1-1', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
