# Generated by Django 5.2.13 on 2026-04-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0002_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
