# Generated by Django 5.2.13 on 2026-04-24 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0003_alter_cliente_email_alter_cliente_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(13, 0))),
                ('activo', models.BooleanField(default=True, help_text='¿Atiende este día?')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_pago',
            field=models.CharField(choices=[('NO', 'No Pagado'), ('PE', 'Pago Pendiente'), ('PA', 'Pagado'), ('RE', 'Reembolsado')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='cita',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de Webpay/MercadoPago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(unique=True),
        ),
    ]
