# Generated by Django 5.2.13 on 2026-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0004_horarioatencion_cita_estado_pago_cita_transaccion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('quienSoy', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('trabajemosJuntos', models.TextField()),
            ],
        ),
    ]
