# Generated by Django 5.2.13 on 2026-04-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0005_sobremi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobremi',
            name='trabajemosJuntos',
            field=models.TextField(max_length=450),
        ),
    ]
