# Generated by Django 5.2.13 on 2026-04-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0008_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremi',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='sobremi',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
