# Generated by Django 5.2.13 on 2026-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0009_sobremi_cv_sobremi_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mp_preference_id',
            field=models.CharField(blank=True, help_text='ID de la preferencia de Mercado Pago', max_length=100, null=True),
        ),
    ]
