# Generated by Django 5.2.13 on 2026-06-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0010_cita_mp_preference_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='cita',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
